### PR TITLE
Add Ratebook base app

### PR DESCRIPTION
**Pull request by o-micron**

### CODE REVIEW

**Review by AmmarYasserHassan — CHANGES_REQUESTED** [review]
# Things to change:
* Use the middleware functions before other routes
* Adjust routes to start with 'api/'
* Check what is to be updated (just the name) 
* Connect with mongoose in the beginning
* Add the config testing

**Comment by o-micron** [comment]
Ok, I moved the middleware part to the top,

I would keep the mongoose.connect to the bottom behind the app.listen because this is cleaner and the database won't be needed until we actually start listening to the port for http requests ...

I have added in readme.md a sample of the `.env` file with the required environment variables needed to run the server, in case of production the file would need to be created since it is ignored by git so no worries in production ...

I will have to change the routing to start with `api/v1.0/`, ok will start working on it

**Review by AmmarYasserHassan — CHANGES_REQUESTED** [review]
Great code 👍🏻
However, I think we should update the following:
* In the route handlers using mongoose methods, some are used using promises and some using async and await. We should follow one way for handling asynchronicity
* Why did you add abstract tests class? it's already confusing enough 😅
* The dependent user/book routes tests are empty
* in Tests.js add a .catch to the promise (it's always advised to add a .catch)
* What does parse.js do?

**Comment by o-micron** [comment]
- The purpose of this repo is to show the different ways for the students, so I want to show how to handle different situations using different methods.
- I added abstract test class in order to show them that it is possible to go for that and not for a direct 1 script full of testing functions + I wanted to start showing them classes with this.sharedState in order to pave the road for the next tutorial which is mainly react 😃 
- parse.js is only mine, I was going to start implementing the tests generator script which will parse testing schema and then generates for us (the TAs) testing scripts effortlessly .. I haven't started yet

**Pull request merged**
